### ISSUE TITLE
CORS issue when not going to HTTPS site

### ISSUE THREAD

**Issue by chayev** [gothamhq/launch-site#2]
When going to http://gothamhq.com/ the below errors happen - resulting in no icons.

Access to font at 'https://gothamhq.com/vendor/font-awesome-4.7.0/fonts/fontawesome-webfont.woff2?v=4.7.0' from origin 'http://gothamhq.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

GET https://gothamhq.com/vendor/font-awesome-4.7.0/fonts/fontawesome-webfont.woff2?v=4.7.0 net::ERR_FAILED

Access to font at 'https://gothamhq.com/vendor/font-awesome-4.7.0/fonts/fontawesome-webfont.woff?v=4.7.0' from origin 'http://gothamhq.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

GET https://gothamhq.com/vendor/font-awesome-4.7.0/fonts/fontawesome-webfont.woff?v=4.7.0 net::ERR_FAILED

Access to font at 'https://gothamhq.com/vendor/font-awesome-4.7.0/fonts/fontawesome-webfont.ttf?v=4.7.0' from origin 'http://gothamhq.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

GET https://gothamhq.com/vendor/font-awesome-4.7.0/fonts/fontawesome-webfont.ttf?v=4.7.0 net::ERR_FAILED

**Comment by FelicianoTech** [comment]
Thanks for catching this. Fixed it by forcing HTTPS on the sever.
